function Y = individualRegressor(a,v)
%INDIVIDUALREGRESSOR
%    OUT1 = INDIVIDUALREGRESSOR(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    04-Dec-2020 23:47:52

a1 = a(1,:);
a2 = a(2,:);
a3 = a(3,:);
a4 = a(4,:);
a5 = a(5,:);
a6 = a(6,:);
v1 = v(1,:);
v2 = v(2,:);
v3 = v(3,:);
v4 = v(4,:);
v5 = v(5,:);
v6 = v(6,:);
t2 = v1.*v2;
t3 = v1.*v3;
t4 = v2.*v3;
t5 = v1.*v5;
t6 = v2.*v4;
t7 = v1.*v6;
t8 = v3.*v4;
t9 = v2.*v6;
t10 = v3.*v5;
t11 = v1.^2;
t12 = v2.^2;
t13 = v3.^2;
t14 = a1+t4;
t15 = a2+t3;
t16 = a3+t2;
t17 = -t2;
t18 = -t3;
t19 = -t4;
t20 = -t6;
t21 = -t7;
t22 = -t10;
t23 = -t11;
t24 = -t12;
t25 = -t13;
t26 = a6+t5+t20;
t27 = a5+t8+t21;
t28 = a4+t9+t22;
Y = reshape([0.0,0.0,0.0,t28,t27,t26,0.0,-a6-t5+t6,t27,t24+t25,t16,-a2+t3,t26,0.0,-a4-t9+t10,-a3+t2,t23+t25,t14,-a5+t7-t8,t28,0.0,t15,-a1+t4,t23+t24,a1,t3,t17,0.0,0.0,0.0,t19,a2,t2,0.0,0.0,0.0,t4,t18,a3,0.0,0.0,0.0,t12+t25,a3+t17,t15,0.0,0.0,0.0,t16,t13+t23,a1+t19,0.0,0.0,0.0,a2+t18,t14,t11+t24,0.0,0.0,0.0],[6,10]);
